site_name: SKE11 Lecture
theme: readthedocs
repo_url: https://github.com/whs/ske11-lecture
docs_dir: .
markdown_extensions: [fenced_code, tables]
pages:
- 'SKE11 Lecture': index.md
- 'Y1S1 - Object Oriented Programming I':
  - 'Class, static, constructor, getter & settor and visibility': oop1/01-class.md
  - 'Inheritance': oop1/02-inheritance.md
  - 'Generics, Polymorphism': oop1/03-generics.md
  - 'Serializable': oop1/serializable.md
  - 'อธิบายโค้ดใน project': oop1/project-explaination.md
- 'Y1S2 - Object Oriented Programming 2':
  - 'Polymorphism และ Interface': oop2/01-polymorph.md
  - 'Parallel ใน Java': oop2/02-parallel.md
- 'Y1S2 - Individual Software Process':
  - 'ถามตอบ JavaScript พื้นฐาน': jsstuff.md
  - 'JavaScript class และ JSHint': jsstuff2.md
- 'Y2S1 - Abstract Data Structure':
  - '21 Aug 2014: Introduction to Sorting': adt/02-lecture.md
  - '21 สิงหาคม 2557: บทนำการเรียงข้อมูล': adt/02-lecture-th.md
  - '25 Aug 2014: Recursion': adt/03-lecture.md
  - '25 สิงหาคม 2557: Recursion (การวนซ้ำ)': adt/03-lecture-th.md
  - '4 September 2014: Recursion (cont.)': adt/04-lecture.md
  - '18 September 2014: Recursion examples': adt/05-lecture.md
  - '22 September 2014: Running time analysis': adt/06-lecture.md
  - 'Big O notation': adt/bigo.md
  - '25 September 2014: List': adt/07-lecture.md
  - '2 October 2014: Tree': adt/08-lecture.md
  - '6 October 2014: Binary Search Tree and postfix computation': adt/09-lecture.md
  - '9 October 2014: Infix to postfix and Stack': adt/10-lecture.md
  - '20 October 2014: Queue, BST Sort, QuickSort': adt/11-lecture.md
  - '3 November 2014: Splay tree, Priority Queue, Heap': adt/12-lecture.md
  - '6 November 2014: Extra class on cache and the goal of computer architecture': adt/12o-lecture.md
  - '10 November 2014: Heap (cont), Heapsort, Symbol table and hashing': adt/13-lecture.md
  - '24 November 2014: Hashtable, fixing hash collision, Graph': adt/14-lecture.md
  - '1 December 2014: Minimum spanning tree, Disjoint set': adt/15-lecture.md
- 'Y2S1 - Computer Organization and Architecture':
  - '3 September 2014: Von Neumann architecture, MIPS ISA, Binary number': comparch/02-lecture.md
  - '3 กันยายน 2557: สถาปัตยกรรม Von Neumann, MIPS ISA, เลขฐานสอง': comparch/02-lecture-th.md
  - 'เริ่มต้น MIPS Assembly': comparch/asm.md
  - "10 September 2014: More in MIPS instructions, 2's complement": comparch/03-lecture.md
  - '24 September 2014: MIPS Multiplication, Division, Floating point representation and arithmetric': comparch/04-lecture.md
  - '1 October 2014: Execution time and CPI': comparch/05-lecture.md
  - '8 October 2014: CPU operation stages, single and multi cycle design': comparch/06-lecture.md
  - '5 November 2014: MIPS Pipeline and hazards': comparch/08-lecture.md
  - '12 November 2014: Overcoming hazards': comparch/09-lecture.md
  - '19 November 2014: Memory and cache design': comparch/10-lecture.md
  - '26 November 2014: Cache performance, associativity, multi level cache': comparch/11-lecture.md
- 'Y2S1 - Communication Skills for SKE':
  - '14 November 2014: Meeting': comskill/01-lecture.md
- 'Y2S2 - Database':
  - '16 January 2015: Introduction to Database Management': database/01-lecture.md
  - '23 January 2015: Entity Relationship Model': database/02-lecture.md
  - '15 February 2015: Relational Data Model, Algebra operations, SQL': database/03-lecture.md
  - '27 February 2015: Anomaly, Constraints, Normal Form': database/04-lecture.md
  - '3 April 2015: Physical Database Design': database/05-lecture.md
- 'Y2S2 - Operating System':
  - '16 January 2015: Introduction': os/01-lecture.md
- 'Y2S2 - Software Specification and Design':
  - '15 January 2015: Analysis, Design, Process': softspec/01-lecture.md
  - 'สรุปบทที่ 1-5 (OOA/D, Iterative process, Inception phase, Requirement)': softspec/01-summary.md
  - '22 January 2015: Class Diagram, Sequence Diagram': softspec/02-lab.md
  - '22 January 2015: Inception, Observer pattern': softspec/02-lecture.md
  - '29 January 2015: Requirements': softspec/03-lab.md
  - '12 February 2015: Quiz answer': softspec/04-lab.md
  - '12 February 2015: Use case, User story, Elaboration': softspec/04-lecture.md
  - '19 February 2015: Milestone, Get out of inception': softspec/05-lab.md
  - '19 February 2015: Diagrams': softspec/05-lecture.md
  - '26 February 2015: Code reuse, design pattern, Good design principle, Data persistent': softspec/06-lab.md
  - '26 February 2015: Object responsibility, GRASP': softspec/06-lecture.md
  - 'ติดตั้ง Play framework บน DigitalOcean': softspec/play-do.md
- 'Y3S1 - Principle of Marketing':
   - 'Exercise for Final Exam': marketing/01-exam.md